version: '3.8'

services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes:
      - goals-data:/data/db
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - logs:/app/logs
      - ./backend:/app # bind mount
      - /app/node_modules
    ports:
      - '80:80'
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - '3000:3000'
    stdin_open: true # -i
    tty: true # -t
    depends_on:
      - backend

volumes:
  goals-data:
  logs:

# networks are automatically created by docker-compose

# docker-compose up -d
# add `--build` to docker-compose command to rebuild image